version: "3.9"

services:
  app:
    image: angeloantonioprisco/ddditserver:localenv-latest
    container_name: ddditserverlocalenv
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # --- MINIO ---
      MINIO_HOST: minio
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ROOT_USERNAME: ${MINIO_ROOT_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      BLOB_STORAGE_BUCKET_MESHES: ${BLOB_STORAGE_BUCKET_MESHES}
      BLOB_STORAGE_BUCKET_MATERIALS: ${BLOB_STORAGE_BUCKET_MATERIALS}

      # --- MONGODB ---
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongodb:27017/${MONGODB_NAME}?authSource=admin
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGODB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_COLLECTION_VERSIONS: ${MONGODB_COLLECTION_VERSIONS}
      MONGODB_COLLECTION_TOKEN_BLACKLIST: ${MONGODB_COLLECTION_TOKEN_BLACKLIST}

      # --- JANUSGRAPH ---
      JANUS_HOST: janusgraph
      JANUS_PORT: 8182
      JANUS_USERNAME: ${JANUS_USERNAME}
      JANUS_PASSWORD: ${JANUS_PASSWORD}

      # --- APP ---
      MODELS_FOLDER_PATH: ${MODELS_FOLDER_PATH}
      JWT_SECRET: ${JWT_SECRET}
      FROM_EMAIL: ${FROM_EMAIL}
      TO_EMAIL: ${TO_EMAIL}
      APP_PASSWORD: ${APP_PASSWORD}

    depends_on:
      janusgraph:
        condition: service_started
      minio:
        condition: service_started
      mongodb:
        condition: service_started